name = "mavkaesu-coop-015"
main = "src/worker.js"
compatibility_date = "2025-08-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "COOP_ROOM"
class_name = "CoopRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CoopRoom"]
