name = "mavkaesu0-1-5"
main = "src/worker.js"
compatibility_date = "2025-08-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "MATCHROOM"
class_name = "MatchRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchRoom"]
